name: PlanetWeather
options:
  bundleIdPrefix: com.cosmicweather
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "15.0"
  developmentLanguage: fr
  defaultConfig: Debug

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: NO

targets:
  PlanetWeather:
    type: application
    platform: iOS
    sources:
      - path: PlanetWeather
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cosmicweather.app
        INFOPLIST_FILE: PlanetWeather/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        ENABLE_PREVIEWS: YES
        SWIFT_EMIT_LOC_STRINGS: YES
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          SWIFT_COMPILATION_MODE: wholemodule
    info:
      path: PlanetWeather/Info.plist
      properties:
        CFBundleDisplayName: Cosmic Weather
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIColorName: LaunchBackgroundColor
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIUserInterfaceStyle: Dark
        NSLocationWhenInUseUsageDescription: Cosmic Weather utilise votre position pour calculer les éclipses visibles et afficher la météo terrestre locale.

schemes:
  PlanetWeather:
    build:
      targets:
        PlanetWeather: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
